### ISSUE TITLE
Separate server.start from other functions ? 

### ISSUE THREAD

**Issue by louislspn** [garrettjoecox/scriptserver#35]
First of all, thank you for this repo, it's awesome !

However, is there a way to start the server on one side and then write / modify functions to do what I want with datas on an other side ? It seems that I need to restart the server every time to get the last version of my code because all functions are in the same file (server.js)

Thank you for your help !

Louis Lespinasse

**Comment by garrettjoecox** [comment]
This is an interesting thought, I will consider this in the upcoming re-write

**Comment by garrettjoecox** [comment]
To answer your question though, currently that is not possible, as the RCON connection waits to connect until ScriptServer has booted the server.

I might remove this limitation and just have it always attempting to connect..

**Comment by garrettjoecox** [comment]
Just pushed a major version update that might help solve this depending on your use case, if you are only using the RconConnection class, you can spin that process up and down at will without affecting a separate JavaServer instance, it will be a bit tricky communicating between the two though if that is a requirement.

Gonna close this for now, since I think that solution is about as close as I can get.
